# Generated by Django 5.0.6 on 2024-05-15 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('affected_brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('malicious_campaign_url', models.URLField()),
                ('malicious_domain_registartion_date', models.DateField()),
                ('malicious_domain_dns_record_a', models.GenericIPAddressField()),
                ('malicious_domain_dns_record_ns', models.GenericIPAddressField()),
                ('malicious_domain_dns_record_mx', models.GenericIPAddressField()),
                ('list_of_matching_keywords', models.TextField()),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('INPROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnalystComment',
            fields=[
                ('analyst_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('comment', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing_tracker.phishingevent')),
            ],
        ),
    ]
